title: "Kendi Temam"
description: "GitHub Pages üzerinde minimal bir tema denemesi."
author: "Süleyman Altun"
baseurl: "" # Proje sayfası için repo adınızı eklemeniz gerekebilir: "/my-github-theme"
url: "https://altunmanx.github.io/" # Kendi GitHub kullanıcı adınıza göre güncelleyin

# Markdown motoru ve tema ayarları
markdown: kramdown

# GitHub Pages’te Jekyll kullanılmasını sağlaması için
plugins:
  - jekyll-feed
  - jekyll-seo-tag
